map $http_x_forwarded_proto $letsbbs_https {
    default off;
    https on;
}

server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;
    charset utf-8;
    client_max_body_size 6m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /uploads/ {
        try_files $uri =404;
        add_header X-Content-Type-Options nosniff always;
        expires 30d;
    }

    location ~* ^/uploads/.*\.php(?:/|$) { return 404; }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_PROXY "";
        fastcgi_param HTTPS $letsbbs_https;
        fastcgi_pass php:9000;
    }

    location ~ /\. { deny all; }
}
